project_id = "mvpucnnobuuvshrxpfmj"

[functions.gut-coach]
verify_jwt = false

[functions.transcribe-audio]
verify_jwt = false

[functions.create-payment]
verify_jwt = false

[functions.stripe-webhook]
verify_jwt = false